sonar.projectKey=microcrm
sonar.organization=rkott0ns
sonar.projectName=MicroCRM
sonar.host.url=https://sonarcloud.io

# Chemins des sources et des tests
sonar.sources=back/src/main/java,front/src
sonar.tests=back/src/test/java,front/src

# Inclusions des tests et exclusions
sonar.test.inclusions=back/src/test/java/**/*Test.java,front/src/**/*.spec.ts
sonar.exclusions=front/src/**/*.spec.ts,front/src/test.ts

# Couverture de code
sonar.coverage.jacoco.xmlReportPaths=back/build/reports/jacoco/test/jacocoTestReport.xml
sonar.typescript.lcov.reportPaths=front/coverage/microcrm/lcov.info
