sonar.projectKey=microcrm-front
sonar.organization=rkott0ns
sonar.projectName=MicroCRM Frontend
sonar.sources=src
# Exclude test files from analysis sources
sonar.exclusions=src/**/*.spec.ts, src/test.ts
# Identify test files
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts
# Coverage report path
sonar.typescript.lcov.reportPaths=coverage/microcrm/lcov.info
sonar.host.url=https://sonarcloud.io
