input {
  tcp {
    port => 5044
    codec => json_lines
  }
  beats {
    port => 5045
  }
}

filter {
  # Enrichissement des logs Spring Boot & Caddy
  if [logger_name] {
    mutate {
      add_field => { "app_name" => "microcrm-backend" }
    }
  } else {
    mutate {
      add_field => { "app_name" => "microcrm-frontend-caddy" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "microcrm-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
