input {
  tcp {
    port => 5044
    codec => json_lines
  }
  gelf {
    port => 12201
  }
  beats {
    port => 5045
  }
}

filter {
  # Enrichissement des logs selon la source (GELF Docker ou TCP direct)
  if [container_name] {
    mutate {
      add_field => { "app_name" => "%{container_name}" }
    }
  } else if [logger_name] {
    mutate {
      add_field => { "app_name" => "microcrm-backend" }
    }
  } else {
    mutate {
      add_field => { "app_name" => "microcrm-frontend-caddy" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    user => "elastic"
    password => "elastic_pass"
    index => "microcrm-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}
